encoding:       utf-8
safe:           true
pygments:       true
paginate:       9
paginate_path:  "page:num"
permalink:      /:year/:month/:day/:title
title:          NOTEPAD
description:    OS Kernel Exploit
author:         iexp
author_email:   firmware7@gmail.com
disqus_id:      iexp
